plugins: 
 - rubocop-rails
 - rubocop-capybara
 - rubocop-rspec
 - rubocop-rspec_rails
 - rubocop-factory_bot

Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
